### ISSUE TITLE
新規登録画面に、ログイン画面へのリンクを追加する

### ISSUE THREAD

**Issue by ulxsth** [24-tomodachi/waffle2#46]
## 概要 

ログイン画面には、以下のように新規登録画面のリンクがある。

![image](https://github.com/24-tomodachi/waffle2/assets/114195789/52c9f13b-c55e-4fa6-90f8-1813c98c8aee)

ただ、新規登録画面にはログイン画面のリンクがない。

![image](https://github.com/24-tomodachi/waffle2/assets/114195789/65e5a06d-101b-4e34-846f-e09bf705ac2f)

そのため、**ログイン画面のリンク**をここに追加する。

## 期待する動作 

新規登録画面から、ログイン画面へ遷移することができる。

**Comment by ayyn0863** [comment]
できました
