### ISSUE TITLE
新規登録画面に、パスワードの再確認項目を追加する

### ISSUE THREAD

**Issue by ulxsth** [24-tomodachi/waffle2#48]
## 概要 

現在、新規登録画面にはパスワードの確認項目がない。

![image](https://github.com/24-tomodachi/waffle2/assets/114195789/5f79704e-36c8-416b-ba32-b4dd9dffc8ca)

そのため、これを追加する。

## 期待する動作 

- [x] 新規登録フォームに「パスワードの再確認」項目が表示される
- [x] 「パスワード」と「パスワードの再確認」内の内容が一致しない場合、エラーが表示される

**Comment by ayyn0863** [comment]
できました
